-- CREATE DATABASE hr;

-- DROP TABLES
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS CUSTOMERS CASCADE;
DROP TABLE IF EXISTS CONTENT CASCADE;
DROP TABLE IF EXISTS PORTFOLIO CASCADE;

-- CUSTOMERS
CREATE TYPE ENUM_INTENTION AS ENUM ('proposta', 'consulta', 'inspiracao');

CREATE TABLE IF NOT EXISTS USERS (
    U_ID SERIAL PRIMARY KEY NOT NULL,
    U_ALIAS VARCHAR(50) NOT NULL UNIQUE,
    U_FIRST_NAME VARCHAR(50) NOT NULL,
    U_LAST_NAME VARCHAR(50) NOT NULL,
    U_EMAIL VARCHAR(50) NOT NULL,
    U_SECRET VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID SERIAL PRIMARY KEY NOT NULL,
    CUST_FIRST_NAME VARCHAR(80) NOT NULL,
    CUST_LAST_NAME VARCHAR(80) NOT NULL,
    CUST_EMAIL VARCHAR(80),
    CUST_MESSAGE VARCHAR(300),
    CUST_INTENTION ENUM_INTENTION
);

CREATE TABLE IF NOT EXISTS CONTENT (
    _ID SERIAL PRIMARY KEY NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    GROUP_NAME VARCHAR(80) NOT NULL,
    LINK VARCHAR(256),
    IS_EXTERNAL BOOLEAN DEFAULT FALSE,
    TEXT VARCHAR(256),
    IMG_SRC VARCHAR(256),
    IMG_SRC_MOBILE VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS PORTFOLIO (
    _ID SERIAL PRIMARY KEY NOT NULL,
    HEADING VARCHAR(100) NOT NULL,
    SUBHEADING VARCHAR(256),
    DESCRIPTION VARCHAR(500) NOT NULL,
    LINK VARCHAR(256)
);